### ISSUE TITLE
some ideas for improvement

### ISSUE THREAD

**Issue by sklaes** [NETWAYS/check_vmware_nsxt#10]
- Introduce a toggle to disable the proxy e.g. --noproxy
- Alarms: Show performance data for high, critical, medium individual e.g. | alarms=12,high=5,critical=3,medium=4;;;0
- Alarms: allow to include / exclude alarms e.g. --exclude=medium or --include 'Certificates/'
- capacity-usage: allow to include / exclude checks, so that you can split it into multiple icinga checks
- Alarms: the help message could point out, that only open alarms will be checks
- Alarms: add a timefilter, so that you can create a volatile check in icinga, to get informed for every new alarm

and by the way, the releases page on exchange.icinga.com lists v0.1.0 as latest
https://exchange.icinga.com/netways/check_vmware_nsxt/releases

**Comment by martialblog** [comment]
Hi, thanks for the feedback. Most of that seems doable I think, but I have to double check. 

Do you want to open a PR? Otherwise I cannot say when stuff will be implemented

**Comment by sklaes** [comment]
It was just a brainstorming on how to improve the script. I haven't implemented the check in Icinga yet and I'm not sure if/which of the above features I need, so I can't say if I will implement any of them

**Comment by martialblog** [comment]
No problem, feedback is always welcome.

**Comment by martialblog** [comment]
@sklaes Could you elaborate what you mean with the "--noproxy" option?

**Comment by sklaes** [comment]
If there is an environment variable defined such as http_proxy, HTTP_PROXY, https_proxy or HTTPS_PROXY, python will use the proxy instead of a direct connection.
Having a lot of checks where some - but not all - need a proxy it is a pain in the a** to configure the no_proxy variable correctly. Something like this could make it a much easier:
```
if args.noproxy:
    os.environ['no_proxy'] = '*'
```

**Comment by martialblog** [comment]
I see. Woudn't unsetting the variable on specific nodes be an option?

I'm not sure yet if this is something that should be included in the code.

**Comment by martialblog** [comment]
@sklaes I'm not a user of the Plugin, can you give some details on this point? 

>  add a timefilter, so that you can create a volatile check in icinga

**Comment by sklaes** [comment]
> @sklaes I'm not a user of the Plugin, can you give some details on this point?
> 
> > add a timefilter, so that you can create a volatile check in icinga

You could set your check interval and the time filter to e.g. 5 min, so you will only get new alerts. The check will automatically reset to green on the next check. (You also need to mark the check as volatile in Icinga to get a notification on the first state change)
This could be useful if you have alerts that you can't solve shortly, but setting a downtime or ack is not an option, because your do not want to miss any new alerts.
However on this check I don't think it is necessary to implement, because your can acknowledge alarms individually in NSX-T and thereby exclude it from the Icinga check.

**Comment by martialblog** [comment]
Thanks again. If need arises we could still do that, for now I'm not sure about implementing this.

**Comment by martialblog** [comment]
We implemented a couple of the suggestions in the new release. We'll update the Icinga Exchange soon.
