### ISSUE TITLE
Non-ASCII character '\xc2' (®)

### ISSUE THREAD

**Issue by uvu9Ba** [NETWAYS/check_vmware_nsxt#2]
On CentOS 7.9 I get following error:

```
SyntaxError: Non-ASCII character '\xc2' in file /usr/local/lib/nagios/plugins/check_vmware_nsxt.py on line 16, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

After removing ® in that line it works.

**Comment by RincewindsHat** [comment]
Hi @uvu9Ba, I could not replicate your error, but it might be fixed with the current master.

**Comment by uvu9Ba** [comment]
@RincewindsHat This as was a `python2` problem after switching to `python3` it worked. But yes the line `# coding:utf-8` fixed the problem with `python2`.  

Maybe `#!/usr/bin/env python3` would be better default shebang? Script is not working for `python2` anyways.
