### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by uvu9Ba** [NETWAYS/check_vmware_nsxt#5]
Hi,
thanks for your effort with that script.

Would it be possible to release it on https://pypi.org ?
For easy installation like `python3 -m pip install -U check_vmware_nsxt` :)

**Comment by lazyfrosch** [comment]
Most Icinga plugins written in Python I know are meant to be very simple to install, in this case copy a single script to plugin dir, and make it executable.

Pypi installation won't bring us any benefit, we recommend most users to install requests from their distributions package system.
