### ISSUE TITLE
(Return code of 127 is out of bounds. Check if plugin exists)

### ISSUE THREAD

**Issue by atmarosi** [NETWAYS/check_vmware_nsxt#8]
I'm able to run the check successfully via the CLI as root, the nagios user annnnd via the 'run command' on the CCM definition.  Any ideas why when it's ran by itself it errors out..?  Using v0.1.2 and python3.6.8

(Return code of 127 is out of bounds. Check if plugin exists)

**Comment by RincewindsHat** [comment]
Hi @atmarosi,
So, if I understand correctly, if you run the plugin as root, it works correctly, but if you run it as the nagios user (debian or ubuntu I assume) like `runuser -u nagios -- check_vmware_nsxt ...` it does not?
Could you paste the complete error message here?

**Comment by atmarosi** [comment]
It work as nagios; just not actually in nagios - outside of CCM -> Run Command.  Can't figure out how to get runuser to work...but su nagios works:
[root@nagios libexec]# runuser -u nagios -- 'python3 /usr/local/nagios/libexec/check_vmware_nsxt.py -A https://URLHERE -u admin -p PASSWORDHERE --insecure -m capacity-usage'
runuser: failed to execute python3 /usr/local/nagios/libexec/check_vmware_nsxt.py -A https://URLHERE -u admin -p PASSWORDHERE --insecure -m capacity-usage: No such file or directory
[root@nagios libexec]# runuser -u nagios -- '/usr/local/nagios/libexec/check_vmware_nsxt.py -A https://URLHERE -u admin -p PASSWORDHERE --insecure -m capacity-usage'
runuser: failed to execute /usr/local/nagios/libexec/check_vmware_nsxt.py -A https://URLHERE -u admin -p PASSWORDHERE --insecure -m capacity-usage: No such file or directory
[root@nagios libexec]#
[root@nagios libexec]# su nagios
[nagios@nagios libexec]$ ./check_vmware_nsxt.py -A 'https://URLHERE' -u admin -p 'PASSWORDHERE' --insecure -m capacity-usage
[OK] 28 info - last update: 2022-10-14 11:20:56

[OK] [INFO] Tier-1 Logical Routers: 2 of 400 (0.5%)
[OK] [INFO] Distributed Firewall Sections: 2 of 5000 (0.04%)

**Comment by RincewindsHat** [comment]
Ok, first things first, for code/shell examples the markdown here gives you the option to mark it them as as such by putting them in "`" quotes (inline) or "```" quotes for blocks.

Your first example doesn't work, because you have the entire command surrounded by `'` quotes and the program `python3 /usr/local/nagios/libexec/check_vmware_nsxt.py ...` does really not exist. The correct way would be to use `python3 "/usr/local/nagios/libexec/check_vmware_nsxt.py" "-A" "http://example.com/..." ...`.

By the way, what is CCM?

So, given the data, I would speculate on a configuration error in the monitoring system.

**Comment by martialblog** [comment]
Closed due to lack of feedback. Can be reopened if necessary
